/**
 * Commit generation type definitions.
 * @module types/commit
 */

/**
 * Represents a single file change in the git diff.
 */
export interface IFileChange {
    /** Relative file path */
    path: string;
    /** Change type */
    status: 'modified' | 'added' | 'deleted' | 'renamed' | 'untracked';
    /** Raw diff content */
    diff?: string;
    /** Number of lines added */
    lines_added?: number;
    /** Number of lines removed */
    lines_removed?: number;
    /** Whether the file is binary */
    is_binary?: boolean;
}

/**
 * Aggregate statistics about the current git changes.
 */
export interface IGitStats {
    /** Total number of files changed */
    total_files: number;
    /** Total lines added across all files */
    total_additions: number;
    /** Total lines deleted across all files */
    total_deletions: number;
    /** File count grouped by extension */
    files_by_extension: Record<string, number>;
    /** List of affected directory paths */
    directories_affected: string[];
}

/**
 * Full analysis context passed to the AI for commit generation.
 */
export interface ICommitAnalysis {
    /** List of individual file changes */
    files: IFileChange[];
    /** Aggregate diff statistics */
    stats: IGitStats;
    /** Project context information */
    project_context: {
        name: string;
        description: string;
        tech_stack: string[];
        target_platform: string;
    };
    /** Recent commit message patterns for style consistency */
    commit_patterns: string;
}

/**
 * A single commit proposal generated by the AI.
 */
export interface ICommitProposal {
    /** Full commit title (e.g., "feat(providers): add multi-provider") */
    title: string;
    /** Commit body description */
    description: string;
    /** Technical details section content */
    technical: string;
    /** Changelog section content */
    changelog: string;
    /** Specific files to include in this commit (undefined = all staged) */
    files?: string[];
}

/**
 * User-provided options for the interactive commit flow.
 */
export interface ICommitOptions {
    /** Description of what was implemented/fixed */
    context: string;
    /** Type of work (feature, fix, refactor, docs, test) */
    workType: string;
    /** List of affected component IDs */
    affectedComponents: string[];
    /** Override commit scope */
    scope?: string;
    /** Whether this is a breaking change */
    breakingChange?: boolean;
    /** Performance impact description */
    performanceImpact?: string;
}
